name: ⭐ Feature request
description: Create a detailed request for a new feature.
title: 'feat: '
labels: ['Feature request']
body:
  - type: markdown
    attributes:
      value: |
        <p align="center">
          <picture>
            <!-- CAMBIAR: Logo de ReVoid -->
            <source
              width="256px"
              media="(prefers-color-scheme: dark)"
              srcset="https://raw.githubusercontent.com/cupul-miu-04/revoid-library/master/assets/revoid-headline/revoid-headline-vertical-dark.svg"
            >
            <img 
              width="256px"
              src="https://raw.githubusercontent.com/cupul-miu-04/revoid-library/master/assets/revoid-headline/revoid-headline-vertical-light.svg"
            >
          </picture>
          <br>
          <!-- CAMBIAR: Enlaces a ReVoid -->
          <a href="https://github.com/cupul-miu-04">
               <picture>
                   <source height="24px" media="(prefers-color-scheme: dark)" srcset="https://i.ibb.co/dMMmCrW/Git-Hub-Mark.png" />
                   <img height="24px" src="https://i.ibb.co/9wV3HGF/Git-Hub-Mark-Light.png" />
               </picture>
           </a>
           <br>
           <br>
           ReVoid Library - Custom implementation
        </p>

        # ReVoid Library feature request

        Before creating a new feature request, please keep the following in mind:

        - **Do not submit a duplicate feature request**: Search for existing feature requests [here](https://github.com/cupul-miu-04/revoid-library/issues?q=label%3A%22Feature+request%22).
        - **Review the contribution guidelines**: Make sure your feature request adheres to it. You can find the guidelines [here](https://github.com/cupul-miu-04/revoid-library/blob/master/CONTRIBUTING.md).
        - **Do not use the issue page for support**: If you need help or have questions, check out other platforms.
  - type: textarea
    attributes:
      label: Feature description
      description: |
        - Describe your feature in detail
        - Add images, videos, links, examples, references, etc. if possible
        - Add the target application name in case you request a new patch
  - type: textarea
    attributes:
      label: Motivation
      description: |
        A strong motivation is necessary for a feature request to be considered.
        
        - Why should this feature be implemented? 
        - What is the explicit use case?
        - What are the benefits?
        - What makes this feature important?
    validations:
      required: true
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your feature request will be closed if you don't follow the checklist below.
      options:
        - label:  I have checked all open and closed feature requests and this is not a duplicate.
          required: true
        - label: I have chosen an appropriate title.
          required: true
        - label: All requested information has been provided properly.
          required: true